const en = {
    search: "Search",
    followers: "Followers",
    following: "Following",
    follow: "Follow",
    unfollow: "Unfollow",
    edit: "Edit",
    user: "User",
    logout: "Logout",
    trophys: "Trophys",
    favourites: "Favourites",
    users: "Users",
    createGroup: "Create group",
    groupName: "Name of group",
    name: "Name",
    create: "Create",
    msg: "Message",
    infoXat: "Information Chat",
    eliminarXat: "Remove Chat",
    participants: "Participants",
    Username: "Username",
    Password: "Password",
    Login: "Login",
    Or_Login_with: "Or Login with",
    Or_Sing_up_with: "Or Sing up with",
    Create_Account: "Create Account",
    e_mail: "e-mail", 
    Data_inici_i_final: "Start and end date",
    Teatre: "theater",
    Categoria: "Category",
    Espectacles: "Shows",
    Musica: "Music",
    Exposicions: "Exhibitions",
    Cinema: "Cinema",
    Divulgacio: "Disclosure",
    Dansa: "Dance",
    Infantil: "Children's",
    Filter: "Filter",
    LlistaPreferits: "Favourites events",
    EliminarReserva: "Delete reservation",
    Reservar: "Book",
    MesInformacio: "More information",
    EsdevenimentOnline: "Online event",
    EsdevenimentTancat: "Closed event",
    editphoto: "Edit photo",
    Exporta: "Export",
}


const es = {
    search: "Buscar",
    followers: "Seguidores",
    following: "Seguidos",
    follow: "Seguir",
    unfollow: "Dejar de seguir",
    edit: "Edita",
    user: "Usuario",
    logout: "Cerrar sesión",
    trophys: "Esculturas",
    favourites: "Favoritos",
    users: "Usuarios",
    createGroup: "Crear grupo",
    groupName: "Nombre del grupo",
    name: "Nombre",
    create: "Crear",
    msg: "Mensaje",
    infoXat: "Información del Chat",
    eliminarXat: "Eliminar Chat",
    participants: "Participantes",
    Username: "Nombre de usuario",
    Password: "Contraseña",
    Login: "Iniciar sesión",
    Or_Login_with: "O inicia sesión con",
    Or_Sing_up_with: "O regísrate con",
    Create_Account: "Crear Cuenta",
    e_mail: "e-mail", 
    Data_inici_i_final: "Fecha de inicio y final",
    Teatre: "Teatro",
    Categoria: "Categoría",
    Espectacles: "Espectáculos",
    Musica: "Música",
    Exposicions: "Exposiciones",
    Cinema: "Cine",
    Divulgacio: "Divulgación",
    Dansa: "Danza",
    Infantil: "Infantil",
    Filter: "Filtrar",
    LlistaPreferits: "Eventos preferidos",
    EliminarReserva: "Eliminar reserva",
    Reservar: "Reservar",
    MesInformacio: "Más información",
    EsdevenimentOnline: "Evento online",
    EsdevenimentTancat: "Evento cerrado",
    editphoto: "Editar foto",
    Exporta: "Exporta",


}

const cat = {
    search: "Buscar",
    followers: "Seguidors",
    following: "Seguits",
    follow: "Seguir",
    unfollow: "Deixar de seguir",
    edit: "Edita",
    user: "Usuari",
    logout: "Tancar sessió",
    trophys: "Escultures",
    favourites: "Preferits",
    users: "Usuarios",
    createGroup: "Crear grupo",
    groupName: "Nom del grupo",
    name: "Nom",
    create: "Crear",
    msg: "Missatge",
    infoXat: "Informació Chat",
    eliminarXat: "Eliminar Chat",
    participants: "Participants",
    Username: "Nom d'usuari",
    Password: "Contrasenya",
    Login: "Iniciar sessió",
    Or_Login_with: "O iniciar sessió amb",
    Or_Sing_up_with: "O registra't con",
    Create_Account: "Crear una compta",
    e_mail: "Correu electrònic", 
    Data_inici_i_final: "Data de inici i final",
    Teatre: "Teatro",
    Categoria: "Categoria",
    Espectacles: "Espectacles",
    Musica: "Música",
    Exposicions: "Exposicions",
    Cinema: "Cine",
    Divulgacio: "Divulgació",
    Dansa: "Dança",
    Infantil: "Infantil",
    Filter: "Filtrar",
    LlistaPreferits: "Events preferits",
    EliminarReserva: "Eliminar reserva",
    Reservar: "Reservar",
    MesInformacio: "Més informació",
    EsdevenimentOnline: "Event online",
    EsdevenimentTancat: "Event tancat",
    editphoto: "Editar foto",
    Exporta: "Exporta",

}


export {en, cat, es};